### ISSUE TITLE
Xamarin wrapper

### ISSUE THREAD

**Issue by Cloze** [Roojin/persian-calendar-view#11] opened 2017-11-23 07:41 UTC
Hi,
thank you for this great component.

add xamarin wrapper too, if possible.

**Comment by mirrajabi** [comment] 2017-11-23 09:58
Hi,
Check if this one helps [https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings](https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings)

**Comment by Cloze** [comment] 2017-11-23 10:01
oooh dear lord ...
i didn't know about that !!! 
thank you

**Comment by mirrajabi** [comment] 2017-12-08 10:35
@Cloze close the issue if the problem is solved.

**Closed** 2017-12-08 11:42 UTC
